### ISSUE TITLE
Set up repo and project

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-kotlin-multiplatform#96]
```[tasklist]
### Tasks
- [x] bug report template
- [x] PR template
- [x] auto-add new issues from this repo to project Team Mobile ([workflow](https://github.com/orgs/getsentry/projects/19/workflows/9198625))
- [x] auto-add new issues with `Platform: KMP` from the docs repo to project Team Mobile ([workflow](https://github.com/orgs/getsentry/projects/19/workflows/9198990))
- [x] auto-add issues with `Platform: KMP` from all other sentry repos to project Team Mobile (not doing this for now, testing project workflows)
- [x] ~~auto-add issues with `Team: Mobile` to project Team Mobile~~ (team labels are deprecated)
- [x] ~~add untriaged label~~ (only for T1 repos)
- [x] Add code owners
- [x] Set up recurring sync calls (every 3 weeks?)
- [x] Add SDK view to project boards (https://github.com/orgs/getsentry/projects/19/views/46)
```

**Comment by marandaneto** [comment]
Also add the non triaged label with open source team, add KMP label to team mobile projects, etc.

**Comment by kahest** [comment]
Created separate [issue for getting started docs](https://github.com/getsentry/sentry-kotlin-multiplatform/issues/110), closing this one
